name: Test
"on":
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
    branches:
      - '*'
jobs:
  test:
    name: Test, Lint, Typecheck and Quick-Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17.3
      - uses: bahmutov/npm-install@v1.8.15
        with:
          useRollingCache: true
      - name: Run Yarn tests
        run: CI=true yarn test
      - name: Run Yarn lint
        run: CI=true yarn lint
      - name: Run TSC Typecheck
        run: CI=true tsc -p tsconfig.json --noEmit --incremental
      - name: Run Yarn Build
        run: CI=true yarn build
  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1.8.15
        with:
          useRollingCache: true
      - uses: cypress-io/github-action@v4
        with:
          install: "false"
          browser: chrome
          start: npm run dev
          wait-on: http://localhost:3000
          config-file: cypress.config.ts
        env:
          PREVIEW_ENDPOINT: "http://localhost:3000"
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: cypress-videos
          path: ./cypress/videos
