name: Test
"on":
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
    branches:
      - '*'
jobs:
  test:
    name: Test, Lint, Typecheck and Quick-Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: "pnpm/action-setup@v6"
        with:
          cache: true
          run_install: true
      - name: Run Yarn tests
        run: pnpm test
      - name: Run Yarn lint
        run: pnpm lint
      - name: Run TSC Typecheck
        run: pnpm tsc --noEmit --incremental
      - name: Run Yarn Build
        run: pnpm build
  cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node-20.11.1-chrome-123.0.6312.58-1-ff-124.0-edge-122.0.2365.92-1
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: "pnpm/action-setup@v6"
        with:
          cache: true
          run_install: true
      - uses: cypress-io/github-action@v6
        with:
          install: "false"
          browser: chrome
          start: npm run dev
          wait-on: http://localhost:3000
          config-file: cypress.config.ts
        env:
          PREVIEW_ENDPOINT: "http://localhost:3000"
          NEXT_PUBLIC_VERCEL_ENV: "production"
          NEXT_PUBLIC_GTM_ID: "GTM-TEST0000"
          NEXT_PUBLIC_POSTHOG_KEY: "phc_test0000"
          NEXT_PUBLIC_POSTHOG_HOST: "https://us.posthog.com"
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: cypress-screenshots
          path: ./cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: cypress-videos
          path: ./cypress/videos
